apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: oneringmsf
spec:
  replicas: 1
  template:
    metadata:
      name: oneringmsf
      labels:
        app: msf
    spec:
      securityContext:
        fsGroup: 412    # Group ID of docker group on k8s nodes.
      containers:
        - name: onering
          image: ilcapone/onering:v4
          imagePullPolicy: Always
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
