apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluend
spec:
  template:
    metadata:
      name: fluend
      labels:
        app: k8fluend
    spec:
      securityContext:
        fsGroup: 412
      containers:
        - name: k8fluend
          image: eu.gcr.io/quickstart-1549448731427/onering:vKiler
          imagePullPolicy: Always
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
