apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluend
spec:
  template:
    metadata:
      name: fluend
      labels:
        app: k8fluend
    spec:
      securityContext:
        fsGroup: 412
      containers:
        - name: k8fluend
          image: ilcapone/onering:v9-StagerG
          imagePullPolicy: Always
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
